pipeline:
  forge_fix:
    image: amilar/droneimg:v30ruby
    environment:
      - RUSTC_WRAPPER=
    commands:
      - cargo build --verbose --all
      - cargo test --verbose --all
      - cd test; ./test.sh; cd -
